Project: Mobile First
juandapps/mobilefirst pull request #1
Opened 2023-03-26 01:57 UTC by juandapps

### 🌐Live Demo: https://dainty-gingersnap-8977c5.netlify.app/

Hello 👋

### 🎯Project Objectives

- Understand how to parse a Figma design to create a UI.
- Use Flexbox to place elements in the page.
- Use CSS Grid to place elements in the page.
- Build a personal portfolio site.

### ✨Animations

- Buttons: Change in state and glowing text effects.
- CTAs: Highlighting and glowing text effects.
- Icons: Scaling effect.
- Project cards: Scaling effect.

### 📝Note

I built the project right away and forgot to commit the skeleton and make a pull request for it, I'm using this pull request for part one and part two.

I'm looking forward to your feedback 😁

2023-03-26 04:04 UTC, franclobo reviewed
Hi @juandapps, 

![terminator](https://user-images.githubusercontent.com/58642949/227754695-2dddf088-1ede-4df5-bea7-50d3ca0b9d0b.gif)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional README file. All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in your repo for professional documentation.

| Expected | Your repo |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/227754623-dd691821-4c36-4145-935e-51895e0aee63.png) | ![image](https://user-images.githubusercontent.com/58642949/227754641-44cbdffd-c3e0-4644-a305-831a16ef0c6e.png) |

- [ ] Please 🙏🏽 complete all the sections, remove the Microverse logo or replace with your own, and ensure that the link to MIT License works as expected.



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-26 04:05 UTC, topeogunleye commented
@juandapps, please kindly update your README file to include all sections in your Table of contents and content 
 - The only optional section is the FAQ

2023-03-26 04:08 UTC, topeogunleye reviewed
Hi @juandapps, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the README file doesn't include all sections in your Table of contents and content

The only optional section is the FAQ

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-26 05:12 UTC, topeogunleye requested changes
Hi @juandapps, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-26 05:12 UTC, topeogunleye commented on index.html
> +    <span class="about-cta">LET'S CONNECT</span>
- [ ] LET'S CONNECT is a header for social media icons. I kindly suggest that you surround your `LET'S CONNECT` text with a header from `h2` to `h6`

2023-03-26 05:12 UTC, topeogunleye commented on css/styles.css
> +#about .card-btn:hover {
- [ ] I kindly suggest that you add the correct button interaction for hover and active (when it's pressed)as shown in the Figma template below:

![Screenshot from 2022-04-27 19-12-50](https://user-images.githubusercontent.com/52934128/165592912-7d8bf224-8e6b-467d-bb19-cf63cd2b40fd.png)

the button on the pressed state has the `background: #2230D2;` and on hover has the `background: #6070FF;`

### EXAMPLE:
**for pressed state**
```
button:active {
   background-color: #2230D2;
}
```
**for hover state**
```
button:hover {
    background-color: #6070FF;
}
```

2023-03-26 05:12 UTC, topeogunleye commented on css/styles.css
> +#projects button {
- [ ] I kindly suggest that you add the correct button interaction for hover and active (when it's pressed) as shown in the Figma template below:

![Screenshot from 2022-04-27 19-12-50](https://user-images.githubusercontent.com/52934128/165592912-7d8bf224-8e6b-467d-bb19-cf63cd2b40fd.png)

the button on the pressed state has the `background: #2230D2;` and on hover has the `background: #6070FF;`

### EXAMPLE:
**for pressed state**
```
button:active {
   background-color: #2230D2;
}
```
**for hover state**
```
button:hover {
    background-color: #6070FF;
}
```

2023-03-26 05:12 UTC, topeogunleye commented on index.html
> +    <div id="accordion" role="tablist">
- [ ] I kindly suggest that you also use a two-level nested `ul` `li` because the technology categories ("Languages", "Frameworks" and "Skills") should also be a `ul`, each of them in a `li`. Kindly see the example below.

## EXAMPLE
```
   <ul>
        <li class="languague">
              <ul>
                  <li><a href="#">JavaScript</a></li>
                  <li><a href="#">HTML</a>
                  <li><a href="#">CSS</a>
             </ul>
         </li>
          <li class="framework">
              <ul>
                  <li><a href="#">Bootstrap</a></li>
                  <li><a href="#">Ruby on Rails</a>
                  <li><a href="#">RSPEC</a>
             </ul>
         </li>
            <li class="skills">
              <ul>
                  <li><a href="#">Code Kit</a></li>
                  <li><a href="#">GitHub</a>
                  <li><a href="#">Codepen</a>
             </ul>
         </li>                                     
</ul>
```

Please note that the above is just an example and may not apply directly to your code.

2023-03-26 05:28 UTC, divinecharlotte requested changes
Hi @juandapps  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive commit messages ✔️ 
- clean code ✔️ 
- Descriptive PR ✔️ 



![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [ ] kindly consider implementing all the requested changes for the first part you will submit  a new PR for the second part

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-26 05:28 UTC, divinecharlotte commented on index.html
> +</nav>
- [ ] kindly consider replacing this nav container with a header container so in order to have a page header on your website

2023-03-26 05:28 UTC, divinecharlotte commented on index.html
> +        <h3>My Logo</h3>
- [ ] kindly consider changing this h3 to a tag This is for three reasons: convention, semantics, and user experience(UX)

2023-03-26 05:28 UTC, divinecharlotte commented on index.html
> +    </div>
- [ ] kindly consider replacing this div with a tag as it will be containing your navigations link in the future for your page and The `nav` tag is for semantics reason again

2023-03-26 05:37 UTC, juandapps commented on index.html
> +    <div id="accordion" role="tablist">
I have them available without the `<ul>` tag because my template is not using them right now 👇

```html
        <section class="accordion-section">
            <h3 id="skills-heading" role="tab" aria-controls="skills-panel">Skills <i class="bx bxs-chevron-right"></i></h3>
            <hr>
        </section>
        <section class="accordion-section">
            <h3 id="frameworks-heading" role="tab" aria-controls="frameworks-panel">Frameworks <i
                    class="bx bxs-chevron-right"></i></h3>
            <hr>
        </section>
```

The technologies being used in the template 👇

```html
        <section class="accordion-section">
            <h3 id="languages-heading" role="tab" aria-controls="languages-panel">Languages
                <i class="bx bxs-chevron-down"></i></h3>
            <div id="languages-panel" class="accordion-panel" role="tabpanel" aria-labelledby="languages-heading">
                <ul class="languages">
                    <li class="language-item">
                        <img src="img/jsEllipse.svg" alt="JavaScript Logo">
                        <span>JavaScript</span>
                    </li>
                    <li class="language-item lang-fix-html-img">
                        <img src="img/htmlEllipse.svg" alt="HTML Logo">
                        <span>HTML</span>
                    </li>
                    <li class="language-item">
                        <img src="img/cssEllipse.svg" alt="CSS Logo">
                        <span>CSS</span>
                    </li>
                </ul>
            </div>
        </section>
```

As you can see above it's using a `<ul>` 👇

```html
                <ul class="languages">
                    <li class="language-item">
                        <img src="img/jsEllipse.svg" alt="JavaScript Logo">
                        <span>JavaScript</span>
                    </li>
                    <li class="language-item lang-fix-html-img">
                        <img src="img/htmlEllipse.svg" alt="HTML Logo">
                        <span>HTML</span>
                    </li>
                    <li class="language-item">
                        <img src="img/cssEllipse.svg" alt="CSS Logo">
                        <span>CSS</span>
                    </li>
                </ul>
```

Thank you 👍

2023-03-26 05:41 UTC, juandapps commented on index.html
> +        <h3>My Logo</h3>
I don't understand what you mean replace `<h3>` with a tag, please be more specific, thank you 👍

2023-03-26 05:47 UTC, topeogunleye commented on index.html
> +        <h3>My Logo</h3>
@juandapps instead of h3 you'll have `<a>My logo</a>`

2023-03-26 05:48 UTC, topeogunleye approved these changes
### Hi @juandapps  

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
* [ ]  Please check my inline comments.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-26 06:28 UTC, topeogunleye approved these changes
Hi @juandapps, 

This is approval for the requested changes by the second reviewer for Mobile First.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 , 

![dwayne-the-rock](https://user-images.githubusercontent.com/52934128/180645370-67438f1f-e27d-4f8b-88d6-1e3474394f0a.gif)

## (Highlights) Good Points: 💪 
* Good commit messages. :heavy_check_mark:
* No linter errors. :heavy_check_mark:
* Followed Github flow :heavy_check_mark:
* Professional README file. :heavy_check_mark:
* PR has a good title and summary :heavy_check_mark:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-26 06:52 UTC, topeogunleye commented on index.html
> +        <h3>My Logo</h3>
- [ ] This is optional as the previous reviewer wasn't clear enough, please kindly surround your logo with an `a` tag because that'll make a logo a link that the user can click on to go back to the homepage

## EXAMPLE
`<a href="#home">My logo</a>`

2023-03-26 23:12 UTC, merged

2023-03-27 15:43 UTC, Alfredbis29 reviewed
Hi @juandapps , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a wrong link for this milestone kindly check again the link you submitted :wink: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-27 16:06 UTC, LionRouge1 reviewed
Hi @juandapps, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is already merged and GitHub features will be unusable when a PR is merged. Please submit another CRR with an open PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-27 17:20 UTC, Kossi-stack reviewed
Hi @juandapps,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
You have submitted a project, that has already been approved. Kindly create a new PR and resubmit

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## 

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-03 14:52 UTC, LionRouge1 reviewed
Hi @juandapps, 

![done](https://media.giphy.com/media/gnE4FFhtFoLKM/giphy.gif)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has already been approved and merged. Kindly create a new PR and resubmit.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**